name: "171_304 to 193 (Fast-DDPM, pred_x0)"

data:
  ext: npz
  image_size: 1024
  dataset_root: /userhome/jeon_mg/workspace/aia_dataset
  train:
    input_dir: train/input
    target_dir: train/target
    batch_size: 1
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: true
    persistent_workers: true
  val:
    input_dir: val/input
    target_dir: val/target
    batch_size: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    persistent_workers: true
  test:
    input_dir: test/input
    target_dir: test/target
    batch_size: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    persistent_workers: true

model:
  name: diffusion
  generator:
    name: UNet2DModel
    args:
      sample_size: 1024
      in_channels: 3     # channel of input+noise image
      out_channels: 1    # channel of target image = channel of noise
      layers_per_block: 2
      block_out_channels: [32, 32, 64, 64, 128, 128, 256, 256]
      down_block_types: [
        "DownBlock2D",
        "DownBlock2D",
        "DownBlock2D",
        "DownBlock2D",
        "DownBlock2D",
        "DownBlock2D",
        "AttnDownBlock2D",
        "AttnDownBlock2D"
      ]
      up_block_types: [
        "AttnUpBlock2D",
        "AttnUpBlock2D",
        "UpBlock2D",
        "UpBlock2D",
        "UpBlock2D",
        "UpBlock2D",
        "UpBlock2D",
        "UpBlock2D",
      ]

params:
  pred: x0
  diffusion:  
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_timesteps: 1000
    fast_ddpm: True
    clip_noise: True
  sampling:
    fixed_initial_noise: True
    out_channels: 1
    eta: 0.0
    timesteps: 100        # skip = num_time_steps // timesteps
  ema:
    active: True
    rate: 0.999
  optimizer:
    name: Adam
    args:
      lr: 0.00001
      betas: [0.5, 0.999]
  grad_clip:
    clip: True
    max_norm: 1.0
  loss:
    name: MSELoss
    args:
      reduction: mean
  num_epochs: 100
  save_img_per_epoch: 10
  save_state_per_epoch: 10
  val_per_epoch: 10
  seed: 42
  float32_matmul_precision: medium
  accelerator: cuda
  devices: [2,3]
  precision: 16-mixed
  strategy: ddp
  output_dir: /userhome/jeon_mg/workspace/results/sdo/diffusion/fast_ddpm/x0
  resume_from: null