name: "171_304 to 193 (Pix2Pix)"

data:
  ext: npz
  image_size: 1024
  train:
    input_dir: /userhome/jeon_mg/workspace/aia_dataset/train/input
    target_dir: /userhome/jeon_mg/workspace/aia_dataset/train/target
    batch_size: 1
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: true
    persistent_workers: true
  val:
    input_dir: /userhome/jeon_mg/workspace/aia_dataset/val/input
    target_dir: /userhome/jeon_mg/workspace/aia_dataset/val/target
    batch_size: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    persistent_workers: true
  test:
    input_dir: /userhome/jeon_mg/workspace/aia_dataset/test/input
    target_dir: /userhome/jeon_mg/workspace/aia_dataset/test/target
    batch_size: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    persistent_workers: true

model:
  name: gan
  generator:
    name: unet
    args:
      input_nc: 2
      output_nc: 1
      num_downs: 6
      ngf: 64
      norm_layer: instance
      use_dropout: false
      init_type: normal
      init_gain: 0.02
  discriminator:
    name: patchgan
    args:
      input_nc: 3
      ndf: 64
      n_layers: 3
      norm_layer: instance
      init_type: normal
      init_gain: 0.02

params:
  ema:
    active: True
    rate: 0.999
  optimizer:
    name: Adam
    args:
      lr: 0.00001
      betas: [0.5, 0.999]
  grad_clip:
    clip: True
    max_norm: 1.0
  loss:
    name: pix2pix
    adversarial:
      name: BCEWithLogitsLoss
      args: null
    reconstruction:
      name: L1Loss
      args:
        lambdaL1: 100
  num_epochs: 100
  save_img_per_epoch: 10
  save_state_per_epoch: 10
  val_per_epoch: 10
  seed: 42
  float32_matmul_precision: medium
  accelerator: cuda
  devices: [2,3]
  precision: 16-mixed
  strategy: ddp
  output_dir: /userhome/jeon_mg/workspace/results/sdo/gan/pix2pix
  resume_from: null