name: "171_304 to 193 (Pix2PixHD)"

data:
  ext: npz
  image_size: 1024
  dataset_root: /userhome/jeon_mg/workspace/aia_dataset
  train:
    input_dir: train/input
    target_dir: train/target
    batch_size: 1
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: true
    persistent_workers: true
  val:
    input_dir: val/input
    target_dir: val/target
    batch_size: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    persistent_workers: true
  test:
    input_dir: test/input
    target_dir: test/target
    batch_size: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    persistent_workers: true

model:
  name: gan
  generator:
    name: pix2pixcc
    args:
      input_ch: 2
      target_ch: 1
      n_gf: 64
      n_downsample: 3
      n_residual: 5
      norm_type: InstanceNorm2d
      padding_type: 'reflection'
      trans_conv: True
  discriminator:
    name: pix2pixhd
    args:
      input_ch: 2
      target_ch: 1
      n_df: 64
      n_D: 2

params:
  ema:
    active: True
    rate: 0.999
  optimizer:
    name: Adam
    args:
      lr: 0.00001
      betas: [0.5, 0.999]
  grad_clip:
    clip: True
    max_norm: 1.0
  loss:
    name: pix2pixhd
    criterion:
      name: MSELoss
      args: null
    FMcriterion:
      name: L1Loss
      args:
        lambda_FM: 10
  num_epochs: 100
  save_img_per_epoch: 10
  save_state_per_epoch: 10
  val_per_epoch: 10
  seed: 42
  float32_matmul_precision: medium
  accelerator: cuda
  devices: [2,3]
  precision: 16-mixed
  strategy: ddp
  output_dir: /userhome/jeon_mg/workspace/results/sdo/gan/pix2pixhd
  resume_from: null