name: "171_304 to 193 (Pix2PixCC)"

data:
  ext: npy
  image_size: 1024
  train:
    input_dir: /home/mgj/workspace/mgjeon/image-to-image/data/sdo/aia_dataset/train/input
    target_dir: /home/mgj/workspace/mgjeon/image-to-image/data/sdo/aia_dataset/train/target
    batch_size: 1
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: true
  val:
    input_dir: /home/mgj/workspace/mgjeon/image-to-image/data/sdo/aia_dataset/val/input
    target_dir: /home/mgj/workspace/mgjeon/image-to-image/data/sdo/aia_dataset/val/target
    batch_size: 1
    shuffle: true
    num_workers: 0
    pin_memory: false
    drop_last: false
  test:
    input_dir: /home/mgj/workspace/mgjeon/image-to-image/data/sdo/aia_dataset/test/input
    target_dir: /home/mgj/workspace/mgjeon/image-to-image/data/sdo/aia_dataset/test/target
    batch_size: 1
    shuffle: false
    num_workers: 0
    pin_memory: false
    drop_last: false

model:
  generator:
    name: default_generator
    args:
      input_ch: 2
      target_ch: 1
      n_gf: 64
      n_downsample: 3
      n_residual: 5
      norm_type: InstanceNorm2d
      padding_type: 'reflection'
      trans_conv: True
  discriminator:
    name: default_discriminator
    args:
      input_ch: 2
      target_ch: 1
      n_df: 64
      ch_balance: 1
      n_D: 2

params:
  ema:
    active: True
    rate: 0.999
  optimizer:
    name: Adam
    args:
      lr: 0.00001
      betas: [0.5, 0.999]
  grad_clip:
    clip: True
    max_norm: 1.0
  loss:
    LSGANcriterion:
      name: MSELoss
      args: 
        lambda_LSGAN: 2.0
    FMcriterion:
      name: L1Loss
      args:
        lambda_FM: 10.0
    CCcriterion:
      name: Concordance
      args:
        n_CC: 4
        lambda_CC: 5.0
  num_epochs: 50
  log_per_iteration: 50
  save_img_per_epoch: 1
  save_state_per_epoch: 1
  save_top_k: -1
  seed: 42
  float32_matmul_precision: "high"
  accelerator: "cuda"
  devices: [0]
  precision: "32-true"
  strategy: "ddp"
  output_dir: /home/mgj/workspace/mgjeon/image-to-image/results/sdo/pix2pixCC/default_small
  resume_from: null